trying new filtering and linter 16

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,7 +44,7 @@ jobs:
                   file_name = os.path.basename(file_path)
                   full_path = os.path.join('extracted_files', file_name)
                   with open(full_path, 'w') as f:
-                      f.write(file_content.strip())  # Strip leading/trailing whitespace
+                      f.write(file_content.strip())
 
           os.makedirs('extracted_files', exist_ok=True)
           for root, dirs, files in os.walk('dotfiles'):
@@ -58,43 +58,54 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y fish emacs
 
-      - name: Install linters
+      - name: Install TOML linter
         run: |
-          pip install tomllint
+          npm install -g @taplo/cli
+          echo "$(npm bin -g)" >> $GITHUB_PATH
 
-      - name: Install lua & luarocks
-      - uses: MunifTanjim/luver-action@v1
-      - run: |
-          luver install lua 5.4.3
-          luver use 5.4.3
-          luver install luarocks 3.8.0
-
-      - name: Install luacheck
-      - run: |
-          luarocks install luacheck
+      - name: Install Lua & LuaCheck
+        run: |
+          sudo apt-get install -y lua5.4 luarocks
+          sudo luarocks install luacheck
+          echo "/usr/local/bin" >> $GITHUB_PATH
 
       - name: Lint Fish files
         run: |
           echo "Linting Fish files..."
+          shopt -s nullglob
           for file in extracted_files/*.fish; do
-            fish -n "$file"
+            if [ -f "$file" ]; then
+              fish -n "$file"
+            fi
           done
 
       - name: Lint Emacs Lisp files
         run: |
           echo "Linting Emacs Lisp files..."
+          shopt -s nullglob
           for file in extracted_files/*.el; do
-            emacs --batch -f batch-byte-compile "$file" || echo "Linting failed for $file"
+            if [ -f "$file" ]; then
+              emacs --batch -f batch-byte-compile "$file" \
+                || echo "Linting failed for $file"
+            fi
           done
 
       - name: Lint TOML files
         run: |
           echo "Linting TOML files..."
+          shopt -s nullglob
           for file in extracted_files/*.toml; do
-            tomllint "$file"
+            if [ -f "$file" ]; then
+              taplo check "$file"
+            fi
           done
 
       - name: Lint Lua files
         run: |
           echo "Linting Lua files..."
-          luacheck extracted_files/*.lua
+          shopt -s nullglob
+          for file in extracted_files/*.lua; do
+            if [ -f "$file" ]; then
+              luacheck "$file"
+            fi
+          done
